#!/usr/bin/env bash
# Install nginx On server

sudo apt-get update

sudo apt-get install -y nginx

sudo sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default

sudo nginx -s reload

echo "Hello World!" | sudo tee /var/www/html/index.html
