#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file``
server_config="
frontend  Mos3aB_frontend
        bind *:80
        mode http
        default_backend Mos3aB_backend
backend Mos3aB_backend
        balance roundrobin
        server 481741-web-01 35.175.64.31:80 check
        server 481741-web-02 52.3.244.199:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

sudo service haproxy restart
