#!/usr/bin/env bash
# This script is displaying
counter=1
while [ $counter -le 20 ]; do
	echo $counter
	case $counter in
	4)
		echo "bad luck form China"
		;;
	9)
		echo "bac luck form Japan"
		;;
	17)
		echo "bad luck from Italy"
		;;
	esac
	((counter++))
done
