#!/usr/bin/env bash
# Bash script that displays all active IPv4 IPs on the machine it’s executed on.

sudo cp /etc/hosts /etc/hosts.backup
echo "127.0.0.2       localhost" | sudo tee /etc/hosts
echo "8.8.8.8         facebook.com" | sudo tee -a /etc/hosts
